version: '3.8'

services:
    nginx:
        container_name: auto_money_nginx
        image: nginx:1.21.6-alpine
        ports:
            - "8123:80"
        volumes:
            - ./apps:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        restart: always
        networks:
            - auto_money_network

    app:
        container_name: auto_money_app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        working_dir: /app
        restart: always
        volumes:
            - ./apps:/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - auto_money_network

    database:
        container_name: auto_money_database
        image: library/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: cdmllove
            MYSQL_USER: mark
            MYSQL_PASSWORD: cdmllove
            MYSQL_DATABASE: milkstore
        volumes:
            - auto_money_data:/var/lib/mysql
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
            - auto_money_network

    phpmyadmin:
        container_name: auto_money_phpmyadmin
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - '1123:80'
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: cdmllove
        networks:
            - auto_money_network

volumes:
    auto_money_data:
        driver: local

networks:
    auto_money_network:
        driver: bridge
